
'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating a professional resume summary using AI.
 *
 * It includes:
 * - generateAiSummary - a function that generates a resume summary based on user inputs.
 * - GenerateAiSummaryInput - The input type for the generateAiSummary function.
 * - GenerateAiSummaryOutput - The return type for the generateAiSummary function.
 */

import {createAI} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateAiSummaryInputSchema = z.object({
  jobTitle: z.string().describe('The desired job title for the resume.'),
  skills: z.string().describe('A comma-separated list of skills.'),
  experience: z.string().optional().describe('The most recent job experience.'),
  language: z.string().describe('The language in which to generate the summary (e.g., "en", "es").'),
  apiKey: z.string().optional().describe('The Google AI API key for authentication.'),
});
export type GenerateAiSummaryInput = z.infer<typeof GenerateAiSummaryInputSchema>;

const GenerateAiSummaryOutputSchema = z.object({
  summary: z.string().describe('A professional resume summary generated by AI.'),
});
export type GenerateAiSummaryOutput = z.infer<typeof GenerateAiSummaryOutputSchema>;

export async function generateAiSummary(input: GenerateAiSummaryInput): Promise<GenerateAiSummaryOutput> {
  // Check if API key is provided (from client) or available in environment
  const apiKey = input.apiKey || process.env.GOOGLE_GENAI_API_KEY || process.env.GOOGLE_GENAI_API_KEY_BACKUP;
  
  console.log('Server - API Key from input:', !!input.apiKey);
  console.log('Server - API Key from input value:', input.apiKey?.substring(0, 10) + '...');
  console.log('Server - API Key from env:', !!process.env.GOOGLE_GENAI_API_KEY);
  console.log('Server - API Key from env value:', process.env.GOOGLE_GENAI_API_KEY?.substring(0, 10) + '...');
  console.log('Server - Final API Key available:', !!apiKey);
  console.log('Server - API Key length:', apiKey?.length);
  console.log('Server - ENABLE_AI_FEATURES:', process.env.ENABLE_AI_FEATURES);
  
  if (!apiKey) {
    console.log('Server - No API key found, returning error message');
    return {
      summary: 'Please configure your Google AI API key in Settings to enable AI-powered summary generation.'
    };
  }
  
  try {
    // Create AI instance with the provided API key
    const ai = createAI(apiKey);
    
    console.log('Server - About to create prompt and flow');
    
    const prompt = ai.definePrompt({
      name: 'generateAiSummaryPrompt',
      input: {schema: GenerateAiSummaryInputSchema},
      output: {schema: GenerateAiSummaryOutputSchema},
      prompt: `Write a professional resume summary in {{{language}}}.
The summary is for a {{{jobTitle}}} with experience in {{{skills}}}.
{{#if experience}} Previously worked as {{{experience}}}. {{/if}}
The summary should be 3-5 lines long, highlight key skills and experiences, and be optimized for applicant tracking systems.
Return only the summary without any additional commentary.`,
    });

    const generateAiSummaryFlow = ai.defineFlow(
      {
        name: 'generateAiSummaryFlow',
        inputSchema: GenerateAiSummaryInputSchema,
        outputSchema: GenerateAiSummaryOutputSchema,
      },
      async input => {
        console.log('Server - Inside flow, about to call prompt');
        const {output} = await prompt(input);
        console.log('Server - Prompt completed successfully');
        return output!;
      }
    );
    
    console.log('Server - About to execute flow');
    const result = await generateAiSummaryFlow(input);
    console.log('Server - Flow completed successfully');
    return result;
  } catch (error) {
    console.error('Error generating AI summary:', error);
    console.error('Error details:', error.message);
    console.error('Error stack:', error.stack);
    
    // Return a helpful fallback message
    return {
      summary: 'Unable to generate AI summary. Please check your API key configuration in Settings or try again later.'
    };
  }
}

// These are now defined inside the function to use the dynamic AI instance
