
'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating a professional cover letter using AI.
 *
 * It includes:
 * - generateCoverLetter - a function that generates a cover letter based on user inputs.
 * - GenerateCoverLetterInput - The input type for the generateCoverLetter function.
 * - GenerateCoverLetterOutput - The return type for the generateCoverLetter function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateCoverLetterInputSchema = z.object({
  companyName: z.string().describe("The name of the company the user is applying to."),
  jobTitle: z.string().describe('The desired job title for the resume.'),
  skills: z.array(z.string()).describe('A list of skills.'),
  experience: z.string().optional().describe('A summary of the most recent job experience.'),
  summary: z.string().describe('The professional summary from the resume.'),
  language: z.string().describe('The language in which to generate the cover letter (e.g., "en", "es").'),
});
export type GenerateCoverLetterInput = z.infer<typeof GenerateCoverLetterInputSchema>;

const GenerateCoverLetterOutputSchema = z.object({
  coverLetter: z.string().describe('A professional cover letter generated by AI.'),
});
export type GenerateCoverLetterOutput = z.infer<typeof GenerateCoverLetterOutputSchema>;

export async function generateCoverLetter(input: GenerateCoverLetterInput): Promise<GenerateCoverLetterOutput> {
  return generateCoverLetterFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateCoverLetterPrompt',
  model: 'gemini-1.5-flash',
  input: {schema: GenerateCoverLetterInputSchema},
  output: {schema: GenerateCoverLetterOutputSchema},
  prompt: `You are a professional resume writer and career coach. Your task is to write a compelling and professional cover letter in {{{language}}}.

Use the following information to draft the letter:
- Company Name: {{{companyName}}}
- Job Title: {{{jobTitle}}}
- Key Skills: {{{skills}}}
- Professional Summary: {{{summary}}}
{{#if experience}}
- Most Recent Experience: {{{experience}}}
{{/if}}

The cover letter should be structured professionally, with a clear introduction, body, and conclusion. It should express enthusiasm for the role at {{{companyName}}}, highlight how the user's skills and experience align with the job title, and end with a strong call to action.

Return only the full text of the cover letter without any additional commentary.`,
});

const generateCoverLetterFlow = ai.defineFlow(
  {
    name: 'generateCoverLetterFlow',
    inputSchema: GenerateCoverLetterInputSchema,
    outputSchema: GenerateCoverLetterOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
