
'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating a professional resume summary using AI.
 *
 * It includes:
 * - generateAiSummary - a function that generates a resume summary based on user inputs.
 * - GenerateAiSummaryInput - The input type for the generateAiSummary function.
 * - GenerateAiSummaryOutput - The return type for the generateAiSummary function.
 */

import { createAI } from '@/ai/genkit';
import { z } from 'genkit';

const GenerateAiSummaryInputSchema = z.object({
  jobTitle: z.string().describe('The desired job title for the resume.'),
  skills: z.string().describe('A comma-separated list of skills.'),
  experience: z.string().optional().describe('The most recent job experience.'),
  language: z.string().describe('The language in which to generate the summary (e.g., "en", "es").'),
  apiKey: z.string().optional().describe('The Google AI API key for authentication.'),
});
export type GenerateAiSummaryInput = z.infer<typeof GenerateAiSummaryInputSchema>;

const GenerateAiSummaryOutputSchema = z.object({
  summary: z.string().describe('A professional resume summary generated by AI.'),
});
export type GenerateAiSummaryOutput = z.infer<typeof GenerateAiSummaryOutputSchema>;

export async function generateAiSummary(input: GenerateAiSummaryInput): Promise<GenerateAiSummaryOutput> {
  // Get API key from input, environment, or use hardcoded fallback
  const apiKey = input.apiKey ||
    process.env.GOOGLE_GENAI_API_KEY ||
    process.env.GOOGLE_GENAI_API_KEY_BACKUP ||
    'AIzaSyAMey9HpHfweRLO62_BOAYJewKqO20Qe54';

  if (!apiKey) {
    return {
      summary: 'Please configure your Google AI API key in Settings to enable AI-powered summary generation.'
    };
  }

  try {
    // Create AI instance with the API key
    const ai = createAI(apiKey);

    const prompt = ai.definePrompt({
      name: 'generateAiSummaryPrompt',
      model: 'googleai/gemini-pro',
      input: { schema: GenerateAiSummaryInputSchema },
      output: { schema: GenerateAiSummaryOutputSchema },
      prompt: `Write a professional resume summary in {{{language}}}.
The summary is for a {{{jobTitle}}} with experience in {{{skills}}}.
{{#if experience}} Previously worked as {{{experience}}}. {{/if}}
The summary should be 3-5 lines long, highlight key skills and experiences, and be optimized for applicant tracking systems.
Return only the summary without any additional commentary.`,
    });

    const generateAiSummaryFlow = ai.defineFlow(
      {
        name: 'generateAiSummaryFlow',
        inputSchema: GenerateAiSummaryInputSchema,
        outputSchema: GenerateAiSummaryOutputSchema,
      },
      async input => {
        const { output } = await prompt(input);
        return output!;
      }
    );

    return generateAiSummaryFlow(input);
  } catch (error) {
    console.error('Error generating AI summary:', error);
    return {
      summary: 'Unable to generate AI summary. Please check your API key configuration in Settings or try again later.'
    };
  }
}

// These are now defined inside the function to use the dynamic AI instance
